# Generated by Django 5.0.4 on 2024-05-07 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_customuser_id_customuser_avatar_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='ID',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='avatar_url',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='biography',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='font_size',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='font_style',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='page_count',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
    ]
