# Generated by Django 5.0.4 on 2024-05-07 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_customuser_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
