# Generated by Django 5.0.4 on 2024-05-13 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_shelf'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddedBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shelf_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('book_id', models.IntegerField()),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('current_page', models.IntegerField(default=0)),
                ('last_update_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('shelf_id', 'user_id', 'book_id')},
            },
        ),
    ]
