# Generated by Django 5.0.4 on 2024-05-13 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_addedbook'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('image_url', models.URLField()),
                ('user_id', models.IntegerField()),
            ],
        ),
    ]
