# Generated by Django 5.0.4 on 2024-05-13 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_audiofolder'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('file_url', models.URLField()),
            ],
        ),
    ]
