# Generated by Django 5.0.4 on 2024-05-13 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_audiofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('book_id', models.IntegerField()),
                ('rating', models.IntegerField()),
            ],
            options={
                'unique_together': {('user_id', 'book_id')},
            },
        ),
    ]
