# Generated by Django 5.0.6 on 2024-05-16 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiofile',
            name='file_url',
            field=models.URLField(default='https://encrypted-tbn3.gstatic.com/images?q=tbn%3AANd9GcS8OUabGQMxidI9ZxjReu3uqZN2Mos32YWdt_dBiixg7Z8H_LG1'),
        ),
        migrations.AlterField(
            model_name='audiofolder',
            name='image_url',
            field=models.URLField(default='https://encrypted-tbn3.gstatic.com/images?q=tbn%3AANd9GcS8OUabGQMxidI9ZxjReu3uqZN2Mos32YWdt_dBiixg7Z8H_LG1'),
        ),
    ]
