# Generated by Django 5.0.4 on 2024-05-16 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReaderInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reader_id', models.IntegerField(default=0, unique=True)),
                ('email', models.CharField(max_length=30, unique=True)),
                ('first_name', models.CharField(default='', max_length=30)),
                ('last_name', models.CharField(default='', max_length=30)),
                ('phone_number', models.CharField(default='', max_length=20)),
                ('biography', models.TextField(default='')),
                ('avatar_url', models.URLField(default='https://cdn-icons-png.flaticon.com/512/1459/1459381.png')),
                ('page_count', models.IntegerField(default=0)),
                ('font_size', models.IntegerField(default=12)),
                ('font_style', models.CharField(default='Arial', max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='audiofile',
            name='file_url',
            field=models.URLField(default='https://encrypted-tbn3.gstatic.com/images?q=tbn%3AANd9GcS8OUabGQMxidI9ZxjReu3uqZN2Mos32YWdt_dBiixg7Z8H_LG1'),
        ),
        migrations.AlterField(
            model_name='audiofolder',
            name='image_url',
            field=models.URLField(default='https://encrypted-tbn3.gstatic.com/images?q=tbn%3AANd9GcS8OUabGQMxidI9ZxjReu3uqZN2Mos32YWdt_dBiixg7Z8H_LG1'),
        ),
    ]
