# Generated by Django 5.0.4 on 2024-05-16 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_audiofile_file_url_alter_audiofolder_image_url'),
        ('app', '0018_readerinfo_alter_audiofile_file_url_and_more'),
    ]

    operations = [
    ]
