# Generated by Django 5.0.4 on 2024-05-17 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_merge_20240516_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='original_font_size',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='readerinfo',
            name='biography',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='readerinfo',
            name='first_name',
            field=models.CharField(default=' ', max_length=30),
        ),
        migrations.AlterField(
            model_name='readerinfo',
            name='last_name',
            field=models.CharField(default=' ', max_length=30),
        ),
        migrations.AlterField(
            model_name='readerinfo',
            name='phone_number',
            field=models.CharField(default=' ', max_length=20),
        ),
        migrations.CreateModel(
            name='ReadingProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_page', models.PositiveIntegerField()),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.book')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.reader')),
            ],
            options={
                'unique_together': {('user_id', 'book_id')},
            },
        ),
    ]
