# Generated by Django 5.0.4 on 2024-05-17 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_readingprocess_book_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingprocess',
            name='last_update_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
