# Generated by Django 5.0.4 on 2024-05-20 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_readerinfo_default_narrator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiofile',
            name='file_url',
            field=models.CharField(default='https://encrypted-tbn3.gstatic.com/images?q=tbn%3AANd9GcS8OUabGQMxidI9ZxjReu3uqZN2Mos32YWdt_dBiixg7Z8H_LG1', max_length=1000),
        ),
    ]
